# local ??
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: "0706"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Dialect ?? ??
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379

# trace Redis를 사용하면서 필요한 로그을 보이게 하는 기능
logging:
  level:
    org.springframework.cache: trace